"use strict";

const { describe, it, before, after } = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const os = require("os");
const { validateIntent } = require("../src/schemas");
const { BWTEngine } = require("../src/bwt");
const { readLinks } = require("../src/links");

// --- Intent links 검증 ---

describe("validateIntent: links 필드", () => {
  const baseIntent = {
    action: "create",
    sourceRef: "30_topics/test/note.md",
    content: "# 테스트",
    record: {
      scopeType: "topic",
      scopeId: "test",
      type: "note",
      title: "테스트",
      sourceType: "candidate"
    }
  };

  it("links 없이도 유효하다 (optional)", () => {
    const result = validateIntent(baseIntent);
    assert.equal(result.valid, true);
  });

  it("올바른 links 배열은 통과한다", () => {
    const intent = {
      ...baseIntent,
      links: [
        { toId: "rec_proj_app_20260301_0001", linkType: "depends_on" },
        { toId: "rec_topic_ref_20260302_0001", linkType: "see_also" }
      ]
    };
    const result = validateIntent(intent);
    assert.equal(result.valid, true);
  });

  it("links가 배열이 아니면 오류", () => {
    const intent = { ...baseIntent, links: "not-array" };
    const result = validateIntent(intent);
    assert.equal(result.valid, false);
    assert.ok(result.errors.some(e => e.includes("배열")));
  });

  it("toId 누락 시 오류", () => {
    const intent = {
      ...baseIntent,
      links: [{ linkType: "related" }]
    };
    const result = validateIntent(intent);
    assert.equal(result.valid, false);
    assert.ok(result.errors.some(e => e.includes("toId")));
  });

  it("잘못된 linkType은 오류", () => {
    const intent = {
      ...baseIntent,
      links: [{ toId: "rec_proj_app_20260301_0001", linkType: "invalid" }]
    };
    const result = validateIntent(intent);
    assert.equal(result.valid, false);
    assert.ok(result.errors.some(e => e.includes("linkType")));
  });

  it("delete/deprecate 시 links는 무시된다", () => {
    const intent = {
      action: "delete",
      recordId: "rec_proj_app_20260301_0001",
      links: [{ toId: "rec_proj_app_20260301_0002", linkType: "invalid_type" }]
    };
    const result = validateIntent(intent);
    assert.equal(result.valid, true); // links 검증 skip
  });

  it("빈 links 배열도 유효하다", () => {
    const intent = { ...baseIntent, links: [] };
    const result = validateIntent(intent);
    assert.equal(result.valid, true);
  });
});

// --- BWT explicit links 통합 ---

function setupBrain() {
  const testRoot = fs.mkdtempSync(path.join(os.tmpdir(), "brain-links-intent-"));
  const dirs = ["00_user", "10_projects", "20_agents", "30_topics", "90_index", "99_policy"];
  for (const d of dirs) {
    fs.mkdirSync(path.join(testRoot, d), { recursive: true });
  }

  fs.writeFileSync(path.join(testRoot, "90_index", "records.jsonl"), "", "utf-8");
  fs.writeFileSync(path.join(testRoot, "90_index", "links.jsonl"), "", "utf-8");
  fs.writeFileSync(path.join(testRoot, "90_index", "tags.json"), JSON.stringify({
    version: "1.0",
    axes: ["domain", "intent"],
    domain: { values: ["memory"], synonyms: {}, banned: [] },
    intent: { values: ["retrieval"], synonyms: {}, banned: [] }
  }, null, 2), "utf-8");
  fs.writeFileSync(path.join(testRoot, "90_index", "folderRegistry.json"), JSON.stringify({
    version: "1.0",
    folders: [
      { path: "00_user/", scopeType: "user", autoCreate: false },
      { path: "10_projects/", scopeType: "project", autoCreate: false },
      { path: "20_agents/", scopeType: "agent", autoCreate: false },
      { path: "30_topics/", scopeType: "topic", autoCreate: true },
      { path: "90_index/", scopeType: null, autoCreate: false },
      { path: "99_policy/", scopeType: null, autoCreate: false }
    ]
  }, null, 2), "utf-8");
  fs.writeFileSync(path.join(testRoot, "90_index", "manifest.json"), JSON.stringify({
    version: "1.0",
    brainRoot: "Brain",
    updatedAt: new Date().toISOString(),
    summary: { totalFiles: 0, byCategory: { policy: 0, user: 0, project: 0, agent: 0, topic: 0, index: 0 } },
    files: []
  }, null, 2), "utf-8");
  fs.writeFileSync(path.join(testRoot, "90_index", "records_digest.txt"),
    "# Brain records_digest.txt\n# Format: recordId | title | summary | tags | status | type | sourceType | updatedAt\n# Auto-generated by brain-cli BWT. Do not edit manually.\n",
    "utf-8"
  );
  fs.writeFileSync(path.join(testRoot, "99_policy", "brainPolicy.md"), "# Brain 운영 정책\n", "utf-8");

  return testRoot;
}

describe("BWT: explicit links 처리", () => {
  let testRoot;
  let firstRecordId;

  before(() => {
    testRoot = setupBrain();

    // 먼저 대상 레코드 생성
    const engine = new BWTEngine(testRoot);
    const result = engine.execute({
      action: "create",
      sourceRef: "30_topics/target/note.md",
      content: "# 대상 노트",
      record: {
        scopeType: "topic",
        scopeId: "target",
        type: "note",
        title: "대상 노트",
        summary: "링크 대상",
        tags: ["domain/memory", "intent/retrieval"],
        sourceType: "candidate"
      }
    });
    assert.equal(result.success, true);
    firstRecordId = result.recordId;
  });

  after(() => {
    if (testRoot) fs.rmSync(testRoot, { recursive: true, force: true });
  });

  it("links 지정 시 explicit 링크가 생성된다", () => {
    const engine = new BWTEngine(testRoot);
    const result = engine.execute({
      action: "create",
      sourceRef: "30_topics/source/decision.md",
      content: "# 결정 문서",
      record: {
        scopeType: "topic",
        scopeId: "source",
        type: "decision",
        title: "결정 문서 — 완전히 다른 제목",
        summary: "explicit link 테스트",
        tags: ["domain/memory", "intent/retrieval"],
        sourceType: "candidate"
      },
      links: [
        { toId: firstRecordId, linkType: "depends_on" }
      ]
    });

    assert.equal(result.success, true);
    assert.equal(result.report.explicitLinked, 1);

    // links.jsonl에서 확인
    const links = readLinks(testRoot);
    const explicit = links.find(l =>
      l.fromId === result.recordId && l.toId === firstRecordId
    );
    assert.ok(explicit);
    assert.equal(explicit.linkType, "depends_on");
  });

  it("links 미지정 시 autoLink fallback이 작동한다", () => {
    const engine = new BWTEngine(testRoot);
    const result = engine.execute({
      action: "create",
      sourceRef: "30_topics/auto/note.md",
      content: "# 자동 링크 테스트",
      record: {
        scopeType: "topic",
        scopeId: "auto",
        type: "note",
        title: "대상 노트 복사본",
        summary: "autoLink fallback 테스트",
        tags: ["domain/memory", "intent/retrieval"],
        sourceType: "candidate"
      }
    });

    assert.equal(result.success, true);
    // explicitLinked는 0, autoLinked는 태그 일치로 1 이상
    assert.equal(result.report.explicitLinked, 0);
    assert.ok(result.report.autoLinked >= 1);
  });

  it("존재하지 않는 toId의 explicit link도 best-effort로 추가된다", () => {
    const engine = new BWTEngine(testRoot);
    const result = engine.execute({
      action: "create",
      sourceRef: "30_topics/orphan/note.md",
      content: "# 고아 링크",
      record: {
        scopeType: "topic",
        scopeId: "orphan",
        type: "note",
        title: "고아 링크 테스트 유니크 제목",
        summary: "없는 대상 링크",
        tags: ["domain/memory"],
        sourceType: "candidate"
      },
      links: [
        { toId: "rec_proj_nonexist_20260101_9999", linkType: "see_also" }
      ]
    });

    assert.equal(result.success, true);
    assert.equal(result.report.explicitLinked, 1);
  });
});
