"use strict";

const fs = require("fs");
const path = require("path");
const { calculateHash, ensureDir } = require("./utils");

/**
 * Brain 초기화 (brain-cli init)
 *
 * 1. Brain/ 디렉토리 + 6개 하위 폴더 생성
 * 2. 5종 인덱스 파일 생성
 * 3. brainPolicy.md 생성
 * 4. 기존 파일은 덮어쓰지 않음 (멱등)
 *
 * @param {string} targetDir - Brain/ 생성 위치의 부모 디렉토리
 * @returns {{ success: boolean, brainRoot: string, created: string[], skipped: string[] }}
 */
function init(targetDir) {
  const brainRoot = path.join(targetDir, "Brain");
  const created = [];
  const skipped = [];

  // 1. 디렉토리 생성
  const dirs = [
    "",
    "00_user",
    "10_projects",
    "20_agents",
    "30_topics",
    "90_index",
    "99_policy",
    "99_policy/templates"
  ];

  for (const dir of dirs) {
    const fullPath = path.join(brainRoot, dir);
    if (!fs.existsSync(fullPath)) {
      ensureDir(fullPath);
      created.push(dir || "Brain/");
    }
  }

  // 2. brainPolicy.md
  _writeIfNotExists(brainRoot, "99_policy/brainPolicy.md", _policyTemplate(), created, skipped);

  // 3. 인덱스 파일 5종
  _writeIfNotExists(brainRoot, "90_index/records.jsonl", "", created, skipped);

  _writeIfNotExists(brainRoot, "90_index/tags.json", JSON.stringify({
    version: "1.0",
    axes: ["domain", "intent"],
    domain: {
      values: ["memory", "auth", "ui", "infra", "data", "devops"],
      synonyms: {},
      banned: []
    },
    intent: {
      values: ["retrieval", "decision", "debug", "onboarding", "reference"],
      synonyms: {},
      banned: []
    }
  }, null, 2), created, skipped);

  _writeIfNotExists(brainRoot, "90_index/folderRegistry.json", JSON.stringify({
    version: "1.0",
    folders: [
      { path: "00_user/", purpose: "사용자 고유 성향/규칙", scopeType: "user", autoCreate: false },
      { path: "10_projects/", purpose: "프로젝트별 격리된 기억", scopeType: "project", autoCreate: false },
      { path: "20_agents/", purpose: "에이전트 정의/역할/룰", scopeType: "agent", autoCreate: false },
      { path: "30_topics/", purpose: "통제된 자율 확장 구역", scopeType: "topic", autoCreate: true },
      { path: "90_index/", purpose: "검색/회수의 핵심 인덱스", scopeType: null, autoCreate: false },
      { path: "99_policy/", purpose: "운영 규칙", scopeType: null, autoCreate: false }
    ]
  }, null, 2), created, skipped);

  _writeIfNotExists(brainRoot, "90_index/records_digest.txt",
    "# Brain records_digest.txt\n# Format: recordId | title | summary | tags | status\n# Auto-generated by brain-cli BWT. Do not edit manually.\n",
    created, skipped
  );

  // manifest.json — brainPolicy.md 해시 포함
  const policyPath = path.join(brainRoot, "99_policy", "brainPolicy.md");
  const manifestContent = _buildManifest(brainRoot, policyPath);
  _writeIfNotExists(brainRoot, "90_index/manifest.json", manifestContent, created, skipped);

  return {
    success: true,
    brainRoot,
    created,
    skipped
  };
}

function _writeIfNotExists(brainRoot, relPath, content, created, skipped) {
  const fullPath = path.join(brainRoot, relPath);
  if (fs.existsSync(fullPath)) {
    skipped.push(relPath);
  } else {
    ensureDir(path.dirname(fullPath));
    fs.writeFileSync(fullPath, content, "utf-8");
    created.push(relPath);
  }
}

function _buildManifest(brainRoot, policyPath) {
  const now = new Date().toISOString();
  const files = [];

  if (fs.existsSync(policyPath)) {
    files.push({
      path: "99_policy/brainPolicy.md",
      hash: calculateHash(policyPath),
      size: fs.statSync(policyPath).size,
      updatedAt: now,
      category: "policy"
    });
  }

  return JSON.stringify({
    version: "1.0",
    brainRoot: "Brain",
    updatedAt: now,
    summary: {
      totalFiles: files.length,
      byCategory: { policy: files.length, user: 0, project: 0, agent: 0, topic: 0, index: 0 }
    },
    files
  }, null, 2);
}

function _policyTemplate() {
  return `# Brain 운영 정책 (brainPolicy)

> 버전: v1.0
> 이 문서는 Brain 장기기억 저장소의 모든 운영 규칙을 정의합니다.
> 에이전트는 Brain 진입 시 이 문서를 최우선으로 참조해야 합니다.

---

## 1. 폴더 구조

| 경로 | 목적 |
|------|------|
| \`00_user/\` | 사용자 고유 성향/규칙 |
| \`10_projects/\` | 프로젝트별 격리된 기억 |
| \`20_agents/\` | 에이전트 정의/역할/룰 |
| \`30_topics/\` | 통제된 자율 확장 구역 |
| \`90_index/\` | 검색/회수의 핵심 인덱스 |
| \`99_policy/\` | 운영 규칙 (이 문서 포함) |

## 2. 역할 정의

- **Memory Lead**: Brain 검색/로드/저장/인덱스 갱신 담당 (단일 writer)
- **Worker**: Memory Packet을 받아 실행, Brain 직접 수정 불가

## 3. BWT (Brain Write Transaction)

- LLM이 Intent JSON 생성 → brain-cli가 파일 I/O + 인덱싱 + 검증
- 9단계 atomic write: .bak 백업 → .tmp 저장 → validate → commit/rollback

## 4. 금지 사항

1. 에이전트 단독 물리 삭제 금지
2. inference의 hardRules/knownDecisions 혼입 금지
3. 등록되지 않은 태그 사용 금지
4. records.jsonl 전량 로드 금지
5. 폴더 자동 생성 제한 (30_topics/만 허용)
6. LLM의 직접 파일 I/O 금지
`;
}

module.exports = { init };
