"use strict";

const fs = require("fs");
const path = require("path");
const { ensureDir, isoNow, safeReadJson } = require("./utils");

// 팀 Brain 초기화에 필요한 최소 인덱스 파일 목록
const INDEX_FILES = {
  "90_index/records.jsonl": "",
  "90_index/records_digest.txt":
    "# Brain records_digest.txt\n# Format: recordId | title | summary | tags | status\n# Auto-generated by brain-cli BWT. Do not edit manually.\n",
  "90_index/tags.json": JSON.stringify({
    version: "1.0",
    axes: ["domain", "intent"],
    domain: {
      values: ["memory", "auth", "ui", "infra", "data", "devops"],
      synonyms: {},
      banned: []
    },
    intent: {
      values: ["retrieval", "decision", "debug", "onboarding", "reference"],
      synonyms: {},
      banned: []
    }
  }, null, 2),
  "90_index/folderRegistry.json": JSON.stringify({
    version: "1.0",
    folders: [
      { path: "10_projects/", purpose: "프로젝트별 격리된 기억", scopeType: "project", autoCreate: false },
      { path: "30_topics/", purpose: "통제된 자율 확장 구역", scopeType: "topic", autoCreate: true },
      { path: "90_index/", purpose: "검색/회수의 핵심 인덱스", scopeType: null, autoCreate: false },
      { path: "projects/", purpose: "팀 프로젝트 공간", scopeType: "project", autoCreate: false }
    ]
  }, null, 2),
  "90_index/manifest.json": JSON.stringify({
    version: "1.0",
    brainRoot: "TeamBrain",
    updatedAt: new Date().toISOString(),
    summary: { totalFiles: 0, byCategory: { policy: 0, user: 0, project: 0, agent: 0, topic: 0, index: 0 } },
    files: []
  }, null, 2)
};

// validate가 요구하는 policy 파일
const POLICY_FILE = {
  "99_policy/brainPolicy.md": `# Brain 운영 정책 (brainPolicy)\n\n> 버전: v1.0 — Team Brain\n\n## 1. 폴더 구조\n\n| 경로 | 목적 |\n|------|------|\n| \`10_projects/\` | 프로젝트별 격리된 기억 |\n| \`30_topics/\` | 통제된 자율 확장 구역 |\n| \`90_index/\` | 검색/회수의 핵심 인덱스 |\n| \`99_policy/\` | 운영 규칙 |\n| \`projects/\` | 팀 프로젝트 공간 |\n\n## 2. BWT (Brain Write Transaction)\n\n- LLM이 Intent JSON 생성 → brain-cli가 파일 I/O + 인덱싱 + 검증\n- 9단계 atomic write\n\n## 3. 금지 사항\n\n1. 에이전트 단독 물리 삭제 금지\n2. records.jsonl 전량 로드 금지\n3. LLM의 직접 파일 I/O 금지\n`
};

// 팀 Brain 기본 디렉토리 목록
const TEAM_BRAIN_DIRS = ["90_index", "10_projects", "30_topics", "projects", "99_policy"];

/**
 * team-config.json 경로를 반환한다.
 * @param {string} teamBrainPath
 * @returns {string}
 */
function configPath(teamBrainPath) {
  return path.join(teamBrainPath, "team-config.json");
}

/**
 * team-config.json을 읽는다.
 * @param {string} teamBrainPath
 * @returns {{ teamName: string, defaultMember: string, projects: Object }}
 */
function readConfig(teamBrainPath) {
  const result = safeReadJson(configPath(teamBrainPath));
  if (!result.ok) {
    throw new Error(`team-config.json 읽기 실패: ${configPath(teamBrainPath)}`);
  }
  return result.data;
}

/**
 * team-config.json을 저장한다.
 * @param {string} teamBrainPath
 * @param {Object} config
 */
function writeConfig(teamBrainPath, config) {
  fs.writeFileSync(configPath(teamBrainPath), JSON.stringify(config, null, 2), "utf-8");
}

/**
 * 팀 Brain을 초기화한다.
 * - teamBrainPath에 90_index/, projects/ 등 기본 구조 생성
 * - 이미 존재하는 파일은 덮어쓰지 않음 (멱등)
 * - team-config.json 생성/갱신
 * - projects/<projectName>/shared/ 생성
 *
 * @param {string} teamBrainPath - 팀 Brain 루트 경로
 * @param {string} projectName - 초기 프로젝트 이름
 * @returns {{ created: string[], skipped: string[] }}
 */
function teamInit(teamBrainPath, projectName) {
  const created = [];
  const skipped = [];

  // 1. 기본 디렉토리 생성
  for (const dir of TEAM_BRAIN_DIRS) {
    const fullPath = path.join(teamBrainPath, dir);
    if (!fs.existsSync(fullPath)) {
      ensureDir(fullPath);
      created.push(dir + "/");
    }
  }

  // 2. 인덱스 + 정책 파일 생성 (없으면만)
  for (const [relPath, content] of Object.entries({ ...INDEX_FILES, ...POLICY_FILE })) {
    const fullPath = path.join(teamBrainPath, relPath);
    if (fs.existsSync(fullPath)) {
      skipped.push(relPath);
    } else {
      ensureDir(path.dirname(fullPath));
      fs.writeFileSync(fullPath, content, "utf-8");
      created.push(relPath);
    }
  }

  // 3. 프로젝트 디렉토리 생성
  const projectSharedPath = path.join(teamBrainPath, "projects", projectName, "shared");
  if (!fs.existsSync(projectSharedPath)) {
    ensureDir(projectSharedPath);
    created.push(`projects/${projectName}/shared/`);
  } else {
    skipped.push(`projects/${projectName}/shared/`);
  }

  // 4. team-config.json 생성/갱신
  const cfgPath = configPath(teamBrainPath);
  let config;
  if (fs.existsSync(cfgPath)) {
    const result = safeReadJson(cfgPath);
    config = result.ok ? result.data : _defaultConfig();
  } else {
    config = _defaultConfig();
  }

  if (!config.projects[projectName]) {
    config.projects[projectName] = {
      members: [],
      createdAt: isoNow()
    };
    created.push("team-config.json (project added)");
  } else {
    skipped.push("team-config.json (project already exists)");
  }

  writeConfig(teamBrainPath, config);

  return { created, skipped };
}

/**
 * 팀원을 프로젝트에 등록하고 개인 공간 디렉토리를 생성한다.
 *
 * @param {string} teamBrainPath - 팀 Brain 루트 경로
 * @param {string} projectName - 대상 프로젝트 이름
 * @param {string} memberName - 등록할 팀원 이름
 * @returns {{ created: string[], skipped: string[], isNew: boolean }}
 */
function teamAddMember(teamBrainPath, projectName, memberName) {
  // 1. team-config.json 존재 확인 (락 획득 전 — 디렉토리 없으면 락 파일도 못 만듦)
  const cfgPath = configPath(teamBrainPath);
  if (!fs.existsSync(cfgPath)) {
    throw new Error(`team-config.json이 없습니다. 먼저 brain-cli team init을 실행하세요: ${cfgPath}`);
  }

  const { acquireLock } = require("./lock");
  const lock = acquireLock(teamBrainPath);
  try {
    const created = [];
    const skipped = [];

    const config = readConfig(teamBrainPath);

    if (!config.projects[projectName]) {
      throw new Error(`프로젝트 '${projectName}'가 없습니다. 먼저 brain-cli team init --project ${projectName}을 실행하세요.`);
    }

    // 2. 팀원 중복 확인 및 추가
    const project = config.projects[projectName];
    const isNew = !project.members.includes(memberName);

    if (isNew) {
      project.members.push(memberName);
      writeConfig(teamBrainPath, config);
    }

    // 3. 팀원 개인 공간 생성
    const memberPath = path.join(teamBrainPath, "projects", projectName, memberName);
    if (!fs.existsSync(memberPath)) {
      ensureDir(memberPath);
      created.push(`projects/${projectName}/${memberName}/`);
    } else {
      skipped.push(`projects/${projectName}/${memberName}/`);
    }

    return { created, skipped, isNew };
  } finally {
    lock.release();
  }
}

function _defaultConfig() {
  return {
    teamName: path.basename(process.cwd()),
    defaultMember: "",
    projects: {}
  };
}

/**
 * 팀 Brain 최근 활동을 조회한다 (관리자 뷰).
 *
 * @param {string} brainRoot - Brain 루트 경로
 * @param {object} opts
 * @param {number} opts.days - 최근 N일 (기본 7)
 * @param {string|null} opts.project - 특정 프로젝트 필터
 * @param {string|null} opts.author - 특정 팀원 필터
 * @param {number} opts.topK - 최대 반환 건수 (기본 20)
 * @returns {{ records: object[], total: number }}
 */
function teamActivity(brainRoot, { days = 7, project = null, author = null, topK = 20 } = {}) {
  const recordsPath = path.join(brainRoot, "90_index", "records.jsonl");
  if (!fs.existsSync(recordsPath)) return { records: [], total: 0 };

  const cutoff = new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();
  const lines = fs.readFileSync(recordsPath, "utf-8").split("\n").filter(l => l.trim());

  const records = [];
  for (const line of lines) {
    try {
      const rec = JSON.parse(line);
      if (rec.status !== "active") continue;
      if (rec.updatedAt < cutoff) continue;
      if (project && rec.scopeId !== project) continue;

      const authorTag = (rec.tags || []).find(t => t.startsWith("team/author:"));
      const recAuthor = authorTag ? authorTag.replace("team/author:", "") : null;
      if (author && recAuthor !== author) continue;

      records.push({
        recordId: rec.recordId,
        scopeId: rec.scopeId,
        type: rec.type,
        title: rec.title,
        summary: rec.summary,
        author: recAuthor,
        updatedAt: rec.updatedAt
      });
    } catch { /* skip malformed */ }
  }

  records.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return { records: records.slice(0, topK), total: records.length };
}

/**
 * 팀 Brain 의사결정 로그를 조회한다.
 *
 * @param {string} brainRoot - Brain 루트 경로
 * @param {object} opts
 * @param {string|null} opts.project - 특정 프로젝트 필터
 * @param {number} opts.topK - 최대 반환 건수 (기본 20)
 * @returns {{ records: object[], total: number }}
 */
function teamDecisions(brainRoot, { project = null, topK = 20 } = {}) {
  const recordsPath = path.join(brainRoot, "90_index", "records.jsonl");
  if (!fs.existsSync(recordsPath)) return { records: [], total: 0 };

  const lines = fs.readFileSync(recordsPath, "utf-8").split("\n").filter(l => l.trim());
  const records = [];

  for (const line of lines) {
    try {
      const rec = JSON.parse(line);
      if (rec.type !== "decision") continue;
      if (rec.status !== "active") continue;
      if (project && rec.scopeId !== project) continue;

      const authorTag = (rec.tags || []).find(t => t.startsWith("team/author:"));
      records.push({
        recordId: rec.recordId,
        scopeId: rec.scopeId,
        title: rec.title,
        summary: rec.summary,
        author: authorTag ? authorTag.replace("team/author:", "") : null,
        sourceType: rec.sourceType,
        updatedAt: rec.updatedAt
      });
    } catch { /* skip malformed */ }
  }

  records.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt));
  return { records: records.slice(0, topK), total: records.length };
}

module.exports = { teamInit, teamAddMember, readConfig, writeConfig, teamActivity, teamDecisions };
